-- Remove demo property
DELETE FROM public.property_fractionalization 
WHERE owner_wallet_address = '0x1111111111111111111111111111111111111111';

-- Restore the 3 main properties to property_fractionalization
INSERT INTO public.property_fractionalization (
    property_name,
    property_location,
    property_image_url,
    original_purchase_price,
    current_speculation_price,
    original_property_value,
    monthly_base_rent,
    total_tokens_available,
    tokens_sold,
    min_investment,
    is_active,
    is_listed_fractionally,
    owner_wallet_address,
    investment_type,
    property_type,
    property_description,
    year_10_trigger_date,
    projected_appreciation_percent,
    appreciation_cap_percent,
    investor_appreciation_burden_percent,
    bedrooms,
    bathrooms,
    square_feet
) VALUES 
-- Mazunte Beach Villa (Art Deco Loft Mexico)
(
    'Mazunte Beach Villa',
    'Mazunte, Mexico', 
    '/src/assets/villa-tulum.jpg',
    129000,
    129000,
    129000,
    748,
    1000000,
    0,
    50,
    true,
    true,
    'system',
    'fractional',
    'villa',
    'Beautiful beachfront villa in Mazunte with stunning ocean views and modern amenities.',
    (CURRENT_DATE + INTERVAL '10 years')::timestamp with time zone,
    181,
    10,
    50,
    3,
    2.5,
    1800
),
-- Bahia Ocean Villa
(
    'Bahia Ocean Villa',
    'Bahia, Brazil',
    '/src/assets/beach-chalet.jpg', 
    120000,
    120000,
    120000,
    635,
    1000000,
    0,
    50,
    true,
    true,
    'system',
    'fractional',
    'villa',
    'Tropical oceanfront villa in Bahia with private beach access and lush gardens.',
    (CURRENT_DATE + INTERVAL '10 years')::timestamp with time zone,
    181,
    10,
    50,
    2,
    2,
    1600
),
-- Ericeira Coastal Villa  
(
    'Ericeira Coastal Villa',
    'Ericeira, Portugal',
    '/src/assets/villa-ericeira-portugal.jpg',
    150000,
    150000, 
    150000,
    2350,
    1000000,
    0,
    50,
    true,
    true,
    'system',
    'fractional',
    'villa',
    'Elegant coastal villa in Ericeira with panoramic Atlantic views and premium finishes.',
    (CURRENT_DATE + INTERVAL '10 years')::timestamp with time zone,
    181,
    10,
    50,
    4,
    3,
    2200
);